export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

//player
export const CREATE_DATA_FOOTBALL_PLAYER_SUCCESS = "CREATE_DATA_FOOTBALL_PLAYER_SUCCESS";
export const CREATE_DATA_FOOTBALL_PLAYER_FAIL = "CREATE_DATA_FOOTBALL_PLAYER_FAIL";
